[package]
name = "alloy-anvil-bug"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.1.4", features = ["full", "node-bindings"] }
anyhow = "1.0"
futures = "0.3"
tokio = { version = "1.0", features = ["full"] }
